routes/admin.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\NotificationController;
use App\Http\Controllers\Admin\SubCategoryController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\BrandController;
use App\Http\Controllers\Admin\ProductController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'category', 'as' => 'category.'], function () {
    Route::get('index', [CategoryController::class, 'index'])
        ->name('index');
    Route::post('store', [CategoryController::class, 'store'])
        ->name('store');
    Route::get('edit/{id}', [CategoryController::class, 'edit'])
        ->name('edit');
    Route::post('update/{id}', [CategoryController::class, 'update'])
        ->name('update');
    Route::post('destroy/{id}', [CategoryController::class, 'destroy'])
        ->name('destroy');
});

Route::group(['prefix' => 'sub-category', 'as' => 'sub-category.'], function () {
    Route::get('index', [SubCategoryController::class, 'index'])
        ->name('index');
    Route::post('store', [SubCategoryController::class, 'store'])
        ->name('store');
    Route::get('edit/{id}', [SubCategoryController::class, 'edit'])
        ->name('edit');
    Route::post('update/{id}', [SubCategoryController::class, 'update'])
        ->name('update');
    Route::post('destroy/{id}', [SubCategoryController::class, 'destroy'])
        ->name('destroy');
});

Route::prefix('banner')->group(function () {
    Route::get('/', [BannerController::class, 'index'])->name('banner');
    Route::get('/add', function () {
        return view('admin.banner.index');
    })->name('banner.add');
    Route::post('/create', [BannerController::class, 'store'])->name('banner.store');
    Route::get('/edit/{id}', [BannerController::class, 'edit'])->name('banner.edit');
    Route::post('/update/{id}', [BannerController::class, 'update'])->name('banner.update');
    Route::get('/status/{id}', [BannerController::class, 'changeStatus'])->name('banner.status');
    Route::delete('/delete/{id}', [BannerController::class, 'delete'])->name('banner.delete');
});

Route::prefix('brand')->group(function () {
    Route::get('/', [BrandController::class, 'index'])->name('brand');
    Route::post('/store', [BrandController::class, 'store'])->name('brand.store');
    Route::get('/edit/{id}', [BrandController::class, 'edit'])->name('brand.edit');
    Route::post('/update/{id}', [BrandController::class, 'update'])->name('brand.update');
    Route::get('/status/{id}', [BrandController::class, 'changeStatus'])->name('brand.status');
    Route::delete('/delete/{id}', [BrandController::class, 'delete'])->name('brand.delete');
});

Route::prefix('product')->group(function () {
    Route::get('/', [ProductController::class, 'index'])->name('product');
    Route::get('/add', [ProductController::class, 'add'])->name('product.add');
    Route::post('/create', [ProductController::class, 'store'])->name('product.store');
    Route::get('/edit/{id}', [ProductController::class, 'edit'])->name('product.edit');
    Route::post('/update/{id}', [ProductController::class, 'update'])->name('product.update');
    Route::delete('/delete/{id}', [ProductController::class, 'delete'])->name('product.delete');
    Route::get('/status/{id}', [ProductController::class, 'changeStatus'])->name('product.status');
    Route::post('/search', [ProductController::class, 'search'])->name('product.search');
    Route::get('/get-categories', [ProductController::class, 'get_categories'])->name('product.get-categories');
    Route::get('/show/{id}', [ProductController::class, 'show'])->name('product.show');
});

Route::prefix('notification')->group(function () {
    Route::get('/', [NotificationController::class, 'index'])->name('notification.index');
    Route::post('/store', [NotificationController::class, 'store'])->name('notification.store');
    Route::get('/edit/{id}', [NotificationController::class, 'edit'])->name('notification.edit');
    Route::post('/update/{id}', [NotificationController::class, 'update'])->name('notification.update');
    Route::get('/status/{id}', [NotificationController::class, 'changeStatus'])->name('notification.status');
    Route::delete('/delete/{id}', [NotificationController::class, 'delete'])->name('notification.delete');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

app/Models/SubCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Class SubCategory
 * @package App\Models
 * @property int $id
 * @property string $image
 * @property int $category_id
 * @property boolean $status
 * @property string $created_at
 * @property string $updated_at
 */
class SubCategory extends Model
{
    use HasFactory;
    protected $guarded = ['id'];
    protected $table = 'subcategories';
    protected $attributes = [
        'status' => true
    ];

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }
}

app/Http/Controllers/Admin/SubCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CrtSubCategoryRequest;
use App\Http\Requests\UptSubCategoryRequest;
use App\Models\Category;
use App\Models\SubCategory;
use App\Traits\StorageImageTrait;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

class SubCategoryController extends Controller
{
    use  StorageImageTrait;

    private $subCategory;
    private $category;

    /**
     * SubCategoryController constructor.
     * @param SubCategory $subCategory
     * @param Category $category
     */
    public function __construct(SubCategory $subCategory, Category $category)
    {
        $this->subCategory = $subCategory;
        $this->category = $category;
    }


    public function index()
    {
        $categories = $this->category->get(['id', 'name']);
        $subCategories = $this->subCategory->get(['id', 'name', 'image', 'category_id', 'status']);
        $inc_add = view('admin.subcategory.add', compact('categories'));
        $inc_list = view('admin.subcategory.inc.list', compact('subCategories'))->render();
        return view('admin.subcategory.index', compact('inc_add', 'inc_list'));
    }

    public function store(CrtSubCategoryRequest $request)
    {
        try {
            $dataInsert = [
                'name'        => $request->input('name'),
                'category_id' => $request->input('category_id'),
            ];
            $image = $request->file('image');
            $imageSource = $this->storageTraitUpload($image, Str::slug($dataInsert['name']));
            $dataInsert['image'] = $imageSource['path'];

            $this->subCategory->create($dataInsert);
        } catch (\Exception $e) {
            $isCreated = false;
            Log::error('message: ' . $e->getMessage() . '--file : ' . $e->getFile() . '--Line : ' . $e->getLine());
        }

        if (isset($isCreated)) {
            $json = [
                'success' => false,
                'data'    => [
                    'type' => 'create',
                ],
                'message' => responseMessage('warning', 'create', __('sub_category')),
            ];
        } else {
            $subCategories = $this->subCategory->get(['id', 'name', 'image', 'category_id', 'status']);
            $inc_list = view('admin.subcategory.inc.list', compact('subCategories'))->render();
            $json = [
                'success' => true,
                'data'    => [
                    'type' => 'create',
                    'html' => $inc_list
                ],
                'message' => responseMessage('success', 'create', __('sub_category'))
            ];
        }

        return response()->json($json);
    }

    public function edit(Request $request, $id)
    {
        $subCategory = $this->subCategory->find($id);
        $categories = $this->category->get(['id', 'name']);
        $inc_add = view('admin.subcategory.add', compact('subCategory', 'categories'))->render();
        return response()->json([
            'data' => [
                'html' => $inc_add
            ]
        ]);
    }

    public function update(UptSubCategoryRequest $request, $id)
    {
        try {
            $subCategory = $this->subCategory->find($id);

            $dataUpdate = $request->only(['name', 'status', 'category_id']);
            if ($request->hasFile('image')) {
                $image = $request->file('image');
                $imageSource = $this->storageTraitUpload($image, Str::slug($dataUpdate['name']));
                $categoryUpdate['image'] = $imageSource['path'];
            }

            $isUpdate = $subCategory->update($dataUpdate);
        } catch (\Exception $e) {
            $isUpdate = false;
            Log::error('message: ' . $e->getMessage() . '--file : ' . $e->getFile() . '--Line : ' . $e->getLine());
        }

        if ($isUpdate) {
            $categories = $this->category->get(['id', 'name']);
            $subCategories = $this->subCategory->get(['id', 'name', 'image', 'category_id', 'status']);
            $inc_add = view('admin.subcategory.add', compact('categories'))->render();
            $inc_list = view('admin.subcategory.inc.list', compact('subCategories'))->render();
            $json = [
                'success' => true,
                'data' => [
                    'type' => 'update',
                    'html' => $inc_list,
                    'add_html' => $inc_add
                ],
                'message' =>  responseMessage('success', 'update', __('sub_category'))
            ];

            if ($request->has('status')) {
                $json['data']['status'] = $request->status;
                $json['message'] = __('change_status_success');
            }
        } else {
            $json = [
                'success' => false,
                'data' => [
                    'type' => 'update',
                ],
                'message' =>  responseMessage('warning', 'update', __('sub_category')),
            ];

            if ($request->has('status')) {
                $json['data']['status'] = $request->status;
                $json['message'] = __('change_status_false');
            }
        }

        return response()->json($json);
    }

    public function destroy(Request $request, $id)
    {
        try {
            $subCategory = $this->subCategory->find($id);
            $subCategory->delete();
        } catch (\Exception $e) {
            $isDeleted = false;
            Log::error('message: ' . $e->getMessage() . '--file : ' . $e->getFile() . '--Line : ' . $e->getLine());
        }

        return response()->json([
            'success' => true,
            'message' => responseMessage('success', 'delete', __('category'))
        ]);
    }
}

resources/views/admin/subcategory/inc/list.blade.php
<hr>
<div class="card">
    <div class="card-header">
        <h5 class="card-header-title"></h5>
    </div>
    <!-- Table -->
    <div class="table-responsive datatable-custom">
        <table id="columnSearchDatatable"
               class="table table-borderless table-thead-bordered table-nowrap table-align-middle card-table"
               data-hs-datatables-options='{
                                 "order": [],
                                 "pageLength": 99,
                                 "language": {
                                    "emptyTable": "Không có dữ liệu",
                                    "zeroRecords": "Không có dữ liệu"
                                   },
                                 "orderCellsTop": true
                               }'>
            <thead class="thead-light">
            <tr>
                <th>#</th>
                <th style="width: 50%">Danh mục cha</th>
                <th style="width: 50%">Danh mục con</th>
                <th style="width: 20%">Trạng thái</th>
                <th style="width: 10%">Hành độn</th>
            </tr>
            <tr>
                <th></th>
                <th>
                    <input type="text" id="column1_search" class="form-control form-control-sm"
                           placeholder="Tìm kiếm">
                </th>

                <th></th>

                <th>
                    <select id="column4_search" class="js-select2-custom" data-hs-select2-options='{
                                          "minimumResultsForSearch": "Infinity",
                                          "customClass": "custom-select custom-select-sm text-capitalize"  }'>
                        <option value="">Tất cả</option>
                        <option value="Hiện">Hiện</option>
                        <option value="Ẩn">Ẩn</option>
                    </select>
                </th>
                <th>

                </th>
            </tr>
            </thead>
            <tbody id="set-rows">
            @foreach($subCategories as $subCategory)
                <tr>
                    <td>{{$subCategory->id}}</td>
                    <td>
                                        <span class="d-block font-size-sm text-body">
                                            {{$subCategory->category->name}}
                                        </span>
                    </td>

                    <td>
                                        <span class="d-block font-size-sm text-body">
                                            {{$subCategory->name}}
                                        </span>
                    </td>
                    <td>
                        <div style="padding: 10px;border: 1px solid;cursor: pointer" data-action="change-status"
                             data-url="{{route('sub-category.update', ['id' => $subCategory->id])}}"
                             data-value="{{$subCategory->status}}"
                             data-name="{{$subCategory->name}}"
                             data-parent="{{$subCategory->category->id}}">
                            <span class="legend-indicator {{$subCategory->status ? 'bg-success' : 'bg-danger'}}"></span>{{$subCategory->status ? 'Hiện' : 'Ẩn'}}
                        </div>
                    </td>
                    <td>
                        <!-- Dropdown -->
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button"
                                    id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                <i class="tio-settings"></i>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" data-action="btnEdit" href="{{route('sub-category.edit', ['id' => $subCategory->id])}}">Sửa</a>
                                <a class="dropdown-item" data-action="btnDelete" data-name="{{$subCategory->name}}" href="{{route('sub-category.destroy', ['id'=> $subCategory->id])}}">Xóa</a>
                            </div>
                        </div>
                        <!-- End Dropdown -->
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <hr>
        <div class="page-area">
            <table>
                <tfoot>

                </tfoot>
            </table>
        </div>
    </div>
</div>