routes/admin.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\NotificationController;
use App\Http\Controllers\Admin\SubCategoryController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\BrandController;
use App\Http\Controllers\Admin\ProductController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'category', 'as' => 'category.'], function () {
    Route::get('index', [CategoryController::class, 'index'])
        ->name('index');
    Route::post('store', [CategoryController::class, 'store'])
        ->name('store');
    Route::get('edit/{id}', [CategoryController::class, 'edit'])
        ->name('edit');
    Route::post('update/{id}', [CategoryController::class, 'update'])
        ->name('update');
    Route::post('destroy/{id}', [CategoryController::class, 'destroy'])
        ->name('destroy');
});

Route::group(['prefix' => 'sub-category', 'as' => 'sub-category.'], function () {
    Route::get('index', [SubCategoryController::class, 'index'])
        ->name('index');
    Route::post('store', [SubCategoryController::class, 'store'])
        ->name('store');
    Route::get('edit/{id}', [SubCategoryController::class, 'edit'])
        ->name('edit');
    Route::post('update/{id}', [SubCategoryController::class, 'update'])
        ->name('update');
    Route::post('destroy/{id}', [SubCategoryController::class, 'destroy'])
        ->name('destroy');
});

Route::prefix('banner')->group(function () {
    Route::get('/', [BannerController::class, 'index'])->name('banner');
    Route::get('/add', function () {
        return view('admin.banner.index');
    })->name('banner.add');
    Route::post('/create', [BannerController::class, 'store'])->name('banner.store');
    Route::get('/edit/{id}', [BannerController::class, 'edit'])->name('banner.edit');
    Route::post('/update/{id}', [BannerController::class, 'update'])->name('banner.update');
    Route::get('/status/{id}', [BannerController::class, 'changeStatus'])->name('banner.status');
    Route::delete('/delete/{id}', [BannerController::class, 'delete'])->name('banner.delete');
});

Route::prefix('brand')->group(function () {
    Route::get('/', [BrandController::class, 'index'])->name('brand');
    Route::post('/store', [BrandController::class, 'store'])->name('brand.store');
    Route::get('/edit/{id}', [BrandController::class, 'edit'])->name('brand.edit');
    Route::post('/update/{id}', [BrandController::class, 'update'])->name('brand.update');
    Route::get('/status/{id}', [BrandController::class, 'changeStatus'])->name('brand.status');
    Route::delete('/delete/{id}', [BrandController::class, 'delete'])->name('brand.delete');
});

Route::prefix('product')->group(function () {
    Route::get('/', [ProductController::class, 'index'])->name('product');
    Route::get('/add', [ProductController::class, 'add'])->name('product.add');
    Route::post('/create', [ProductController::class, 'store'])->name('product.store');
    Route::get('/edit/{id}', [ProductController::class, 'edit'])->name('product.edit');
    Route::post('/update/{id}', [ProductController::class, 'update'])->name('product.update');
    Route::delete('/delete/{id}', [ProductController::class, 'delete'])->name('product.delete');
    Route::get('/status/{id}', [ProductController::class, 'changeStatus'])->name('product.status');
    Route::post('/search', [ProductController::class, 'search'])->name('product.search');
    Route::get('/get-categories', [ProductController::class, 'get_categories'])->name('product.get-categories');
    Route::get('/show/{id}', [ProductController::class, 'show'])->name('product.show');
});

Route::prefix('notification')->group(function () {
    Route::get('/', [NotificationController::class, 'index'])->name('notification.index');
    Route::post('/store', [NotificationController::class, 'store'])->name('notification.store');
    Route::get('/edit/{id}', [NotificationController::class, 'edit'])->name('notification.edit');
    Route::post('/update/{id}', [NotificationController::class, 'update'])->name('notification.update');
    Route::get('/status/{id}', [NotificationController::class, 'changeStatus'])->name('notification.status');
    Route::delete('/delete/{id}', [NotificationController::class, 'delete'])->name('notification.delete');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Category
 * @package App\Models
 * @property int $id
 * @property string $image
 * @property boolean $status
 * @property string $created_at
 * @property string $updated_at
 */
class Category extends Model
{
    use HasFactory;

    protected $guarded = ['id'];
    protected $table = 'categories';
    protected $attributes = [
      'status' => true
    ];

    public function subCategories()
    {
        return $this->hasMany(SubCategory::class, 'category_id');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CrtCategoryRequest;
use App\Http\Requests\UptCategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Traits\StorageImageTrait;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

class CategoryController extends Controller
{
    use  StorageImageTrait;
    private $category;

    /**
     * CategoryController constructor.
     * @param Category $category
     */
    public function __construct(Category $category)
    {
        $this->category = $category;
    }


    public function index()
    {
        $categories = $this->category->all();
        $inc_add = view('admin.category.add')->render();
        $inc_list = view('admin.category.inc.list', compact('categories'))->render();
        return view('admin.category.index', compact('inc_list', 'inc_add'));
    }

    /**
     * create new category product
     * @param Request $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        try {
            $name = $request->input('name');
            $image = $request->file('image');
            $imageSource = $this->storageTraitUpload($image, Str::slug($name));
            $categoryInsert = [
                'name' => $name,
                'image'=> $imageSource['path']
            ];
            $this->category->create($categoryInsert);
        } catch (\Exception $e) {
            $isCreated = false;
            Log::error('message: ' . $e->getMessage() . '--file : ' . $e->getFile() . '--Line : ' . $e->getLine());
        }

        if (isset($isCreated)) {
            $json = [
                'success' => false,
                'data' => [
                    'type' => 'create',
                ],
                'message' =>  responseMessage('warning', 'create', __('category')),
            ];
        }else{
            $categories = $this->category->all();
            $inc_list = view('admin.category.inc.list', compact('categories'))->render();
            $json = [
                'success' => true,
                'data' => [
                    'type' => 'create',
                    'html' => $inc_list
                ],
                'message' =>  responseMessage('success', 'create', __('category'))
            ];
        }

        return response()->json($json);
    }

    public function edit(Request $request, $id)
    {
        $category = $this->category->find($id);
        $inc_add = view('admin.category.add', compact('category'))->render();
        return response()->json([
            'data' => [
                'html' => $inc_add
            ]
        ]);
    }

    public function update(UptCategoryRequest $request, $id)
    {
        try {
            $category = $this->category->find($id);

            $categoryUpdate = $request->only(['name', 'status']);
            if ($request->hasFile('image')) {
                $image = $request->file('image');
                $imageSource = $this->storageTraitUpload($image, Str::slug($categoryUpdate['name']));
                $categoryUpdate['image'] = $imageSource['path'];
            }

            $isUpdate = $category->update($categoryUpdate);
        } catch (\Exception $e) {
            $isUpdate = false;
            Log::error('message: ' . $e->getMessage() . '--file : ' . $e->getFile() . '--Line : ' . $e->getLine());
        }

        if ($isUpdate) {
            $categories = $this->category->all();
            $inc_add = view('admin.category.add')->render();
            $inc_list = view('admin.category.inc.list', compact('categories'))->render();
            $json = [
                'success' => true,
                'data' => [
                    'type' => 'update',
                    'html' => $inc_list,
                    'add_html' => $inc_add
                ],
                'message' =>  responseMessage('success', 'update', __('category'))
            ];

            if ($request->has('status')) {
                $json['data']['status'] = $request->status;
                $json['message'] = __('change_status_success');
            }
        }else{
            $json = [
                'success' => false,
                'data' => [
                    'type' => 'update',
                ],
                'message' =>  responseMessage('warning', 'update', __('category')),
            ];

            if ($request->has('status')) {
                $json['data']['status'] = $request->status;
                $json['message'] = __('change_status_false');
            }
        }

        return response()->json($json);

    }

    public function destroy(Request $request, $id)
    {
        try {
            $category = $this->category->find($id);
            $category->delete();
        } catch (\Exception $e) {
            $isDeleted = false;
            Log::error('message: ' . $e->getMessage() . '--file : ' . $e->getFile() . '--Line : ' . $e->getLine());
        }

        if ($request->ajax()) {
            return response()->json([
                'success' => true,
                'message' => responseMessage('success', 'delete', __('category'))
            ]);
        }

        if (isset($isDeleted)) {
            return redirect()->back()->withErrors([
                'error' => responseMessage('warning', 'delete', __('category')),
            ]);
        }

        return redirect()->route('category.index')
            ->with('message', responseMessage('success', 'create', __('category')))
            ->with('type', __('type_success'));
    }
}

resources/views/admin/category/add.blade.php
<form data-name="category" action="{{ isset($category) ? route('category.update', ['id' => $category->id]) : route('category.store')}}" method="post" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-6">
            <div class="form-group  lang_form" id="en-form">
                <label class="input-label" for="exampleFormControlInput1">Tên danh mục</label>
                <input type="text" name="name" class="form-control" placeholder="Tên" value="{{isset($category) ? $category->name: ''}}" required>
            </div>
        </div>
        <div class="col-6 from_part_2">
            <label>Hình ảnh</label><small style="color: red">* ( Tỷ lệ 3:1 )</small>
            <div class="custom-file">
                <input type="file" name="image" id="customFileEg1" class="custom-file-input" accept=".jpg, .png, .jpeg, .gif, .bmp, .tif, .tiff|image/*" {{isset($category) ? '' : 'required'}}>
                <label class="custom-file-label" for="customFileEg1">Chọn ảnh</label>
            </div>
        </div>
        <div class="col-12 from_part_2">
            <div class="form-group">
                <hr>
                <center>
                    <img style="width: 30%;border: 1px solid; border-radius: 10px;" id="viewer" src="{{isset($category) ? $category->image : asset('admin/assets/img/900x400/img1.jpg')}}" onerror="this.onerror=null; this.src='{{asset('admin/assets/img/900x400/img1.jpg')}}'" alt="image" />
                </center>
            </div>
        </div>
    </div>

    <hr>
    <button type="submit" class="btn btn-primary">{{isset($category) ? 'Cập nhật' : 'Thêm'}}</button>
</form>

resources/views/admin/category/index.blade.php
@extends('layouts.admin.app')

@section('title', 'Danh mục sản phẩm')

@section('content')
    <div class="content container-fluid">
        <!-- Page Header -->

        <div class="page-header">
            <div class="row align-items-center">
                <div class="col-sm mb-2 mb-sm-0">
                    <h1 class="page-header-title"><i class="tio-add-circle-outlined"></i> Thêm Mới Danh Mục Sản Phẩm</h1>
                </div>
            </div>
        </div>
        <!-- End Page Header -->
        @if($errors->any())
            <p id="error-message" data-message="{{$errors->first()}}"></p>
        @endif
        @if(session('message') && session('type'))
            <p id="session-message" data-message="{{session('message')}}" data-type="{{session('type')}}"></p>
            @php(session()->forget(['message', 'type']))
        @endif
        <div class="row gx-2 gx-lg-3">
            <div class="col-sm-12 col-lg-12 mb-3 mb-lg-2 category-form">
                {!! $inc_add !!}
            </div>
            <div class="col-sm-12 col-lg-12 mb-3 mb-lg-2 category-list">
                {!! $inc_list !!}
            </div>
            <!-- End Table -->
        </div>
    </div>
@endsection
@section('js')
    <script src="{{asset('admin/assets/js/common.js')}}"></script>
    <script src="{{asset('admin/assets/js/message.js')}}"></script>
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#viewer').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $(document).on('change', '#customFileEg1', function (){
            readURL(this);
        })

    </script>
    <script>
        $(function () {
            $(document).on('click', '*[data-action="btnDelete"]', function () {
                event.preventDefault();
                var name = $(this).attr('data-name')
                var url = $(this).attr('href');
                var currentElement = $(this);

                app.deleteObject(`Danh mục sản phẩm ${name} sẽ bị xóa bỏ?`, url, currentElement)

            });
            $(document).on('click', '*[data-action="btnEdit"]', function () {
                event.preventDefault();
                var url = $(this).attr('href');
                var currentElement = $(this);
                let ajaxCall = $.ajax({
                    url     : url,
                    type    : 'get',
                    headers : {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                })

                ajaxCall.done(function (json) {
                    $('.category-form').html(json['data']['html'])
                });

            });
            $(document).on('submit', '*[data-name="category"]', function (e) {
                event.preventDefault();
                let currentElement = $(this)
                let url = currentElement.attr('action')
                var formData = new FormData(this);

                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                $.post({
                    url: url,
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    beforeSend: function () {
                        $('#loading').show();
                    },
                    success: function (json) {
                        if (json['success']) {
                            $('.category-list').html(json['data']['html']);
                            app.refreshDataTable();
                            toastr.options.timeOut = 3000;
                            if (json['data']['type'] === 'create') {
                                $('input[name="name"]').val('')
                                $('input[name="image"]').val('')
                                $('#viewer').attr('src','{{asset('admin/assets/img/900x400/img1.jpg')}}')
                                toastr.success(json['message']);
                            } else {
                                $('.category-form').html(json['data']['add_html'])
                                toastr.info(json['message']);
                            }
                        } else {
                            toastr.options.timeOut = 3000;
                            toastr.warning(json['message'])
                        }
                    },
                    error: function (json) {
                        if (json['status'] === 422) {
                            let error = json['responseJSON']['message']
                            toastr.options.timeOut = 3000;
                            toastr.error(error)
                        }
                    },
                    complete: function () {
                        $('#loading').hide();
                    },
                });
            })
            $(document).on('click', '*[data-action="change-status"]', function () {
                event.preventDefault();
                let url = $(this).attr('data-url');
                let currentElement = $(this);
                let name = currentElement.attr('data-name');
                let status = currentElement.attr('data-value');
                if (status == true) {
                    currentElement.attr('data-value', '0');
                } else {
                    currentElement.attr('data-value', '1');
                }
                let statusUpdate = status == true ? 0 : 1
                let ajaxCall = $.ajax({
                    url     : url,
                    type    : 'post',
                    data    : {
                        'status' : statusUpdate,
                        'name' : name
                    },
                    dataType: 'json',
                    beforeSend: function () {
                        $('#loading').show();
                    },
                    complete: function () {
                        $('#loading').hide();
                    },
                    headers : {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                })

                ajaxCall.done(function (json) {
                    if (json['success']) {
                        $('.category-list').html(json['data']['html']);
                        app.refreshDataTable();
                        toastr.options.timeOut = 3000;
                        toastr.info(json['message']);
                    } else {
                        toastr.options.timeOut = 3000;
                        toastr.warning(json['message'])
                    }
                });
            });
        });
    </script>
@endsection